# Generated by Django 5.1.1 on 2024-10-12 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GadResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('question_2', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('question_3', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('question_4', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('question_5', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('question_6', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('question_7', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('total_score', models.IntegerField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('is_first_submission', models.BooleanField(default=False)),
                ('prediction_ready', models.BooleanField(default=False)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
