# Generated by Django 5.1.1 on 2024-10-12 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gadresponse_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gadresponse',
            name='is_first_submission',
        ),
        migrations.RemoveField(
            model_name='gadresponse',
            name='prediction_ready',
        ),
        migrations.RemoveField(
            model_name='gadresponse',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='gadresponse',
            name='token_expiration',
        ),
        migrations.RemoveField(
            model_name='gadresponse',
            name='total_score',
        ),
        migrations.AddField(
            model_name='gadresponse',
            name='difficulty',
            field=models.CharField(default='Not specified', max_length=50),
        ),
        migrations.AddField(
            model_name='gadresponse',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gadresponse',
            name='question_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gadresponse',
            name='question_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gadresponse',
            name='question_3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gadresponse',
            name='question_4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gadresponse',
            name='question_5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gadresponse',
            name='question_6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gadresponse',
            name='question_7',
            field=models.IntegerField(),
        ),
    ]
