# Generated by Django 5.1.1 on 2024-10-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_gadresponse_is_first_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadresponse',
            name='is_filled',
            field=models.IntegerField(default=0),
        ),
    ]
